### ISSUE TITLE
sftp configurations

### ISSUE THREAD

**Issue by Aub-C** [defectivebit/docker-crushftp#1]
Hello,

Are you able to add new users and change the configuration files from version control? 

How are you handling the configurations?

Thanks,

Aub

**Comment by defectivebit** [comment]
Hi Aub,

I’ve been working over the past few days to make the container store CrushFTP's configuration in the container's `/config` directory. Then, you can share an outside folder to that directory, and save the configuration portably off-container. That will allow you to use git or many other methods to manage the configuration. 

I hope to have this finished by the end of the week, but I am quite busy and have no fixed timeline.

Thanks,
Brian Tkatch

**Comment by Aub-C** [comment]
Thanks for the update, Brian. I look forward to the update. 

-Aub-C

**Comment by defectivebit** [comment]
Hi Aub,

Apologies for the delays, I have been pecking at this over the last several days and while I believe that I am close I am not finished yet. I do hope to be done this as soon as possible and I appreciate your patience.

Thanks,
Brian Tkatch

**Comment by Aub-C** [comment]
Thanks again, Brian. I appreciate the status update.

-Aub

**Comment by defectivebit** [comment]
Hi Aub,

I have modified how the container is built and executed to support persisting CrushFTP's configuration directory. Now, you can persist CrushFTP's entire installation and configuration by sharing the container's `/var/opt/CrushFTP8_PC` directory with the host (e.g. use `-v "/mypath/":"/var/opt/CrushFTP8_PC":rw` with `docker run`).

This directory includes files such as logs and large binaries that don't naturally lend themselves well to traditional version control tools like git, so (using git as an example) you may need to write a .gitignore that excludes these types of files. This should be fairly straightforward, but I can assist with this if you'd like.

Please let me know if you have any further questions. If not, I'll go ahead and close this issue.

Thanks,
Brian Tkatch

**Comment by defectivebit** [comment]
Hi Aub,

As I haven't heard back from you, I will be closing this issue. If you do have any concerns, please feel free to re-open it with a reply.

Thanks,
Brian Tkatch

**Comment by Aub-C** [comment]
Hi Brian,

Sorry for the late response. I've been out on vacation. I'll be working with this, this week. The code looks great!

Thanks,

Aubrey
